[project]
name = "test-payment-endpoint"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Eugene Safronov", email = "ysafr7@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.0",
    "flask-migrate>=4.1.0",
    "flask-sqlalchemy>=3.1.1",
    "psycopg[binary]>=3.3.5",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
